version: "3.9"

services:
  jekyll:
    image: jekyll/jekyll:4
    working_dir: /srv/jekyll
    environment:
      - JEKYLL_ENV=development
    command: >-
      sh -c "bundle install && bundle exec jekyll serve
      --livereload --drafts --host 0.0.0.0"
    ports:
      - "4000:4000"   # Site
      - "35729:35729" # LiveReload
    volumes:
      - .:/srv/jekyll
      - bundle:/usr/local/bundle

volumes:
  bundle:

